/* ============================================================
   INGLY DESIGN — SEED DEL CATALOGO
   ------------------------------------------------------------
   Fonte di partenza per la generazione di data/products.json.

   Ogni voce:
   [ nome, sottotitolo, sottocategoria, materiali[], tecnologie[],
     dimensioni{}, usi[], pubblico, dettaglio, personalizzazione[] ]

   REGOLE
   - `nome` è nomenclatura INGLY originale (vedi docs/MIGRATION-MAP.md §4).
     Nessun nome del sito di riferimento può comparire qui: il controllo è
     automatico in scripts/validate-data.mjs → checkReservedNames().
   - `dettaglio` è testo originale, scritto per INGLY DESIGN. Non è tradotto,
     riassunto o riscritto da fonti di terzi.
   - `materiali` e `tecnologie` devono esistere in data/materials.json e
     data/technologies.json. `usi` in data/migration.json → collections.

   Rigenerazione:  npm run build:catalog
   ============================================================ */

export const PREFIX = {
  'soluzioni-menu': 'sm',
  'tavola-cucina': 'tc',
  'wood-art-design': 'wd',
  'oggettistica': 'og',
  'targhe-insegne': 'ti',
  'gadget': 'gd',
  'casa': 'cs',
  'kids': 'kd',
  'arte-movimento': 'am',
  'tech': 'th',
  'carta-packaging': 'cp',
  'plexi-metallo': 'pm',
  'eventi': 'ev'
};

export const SEED = {

  /* ── SOLUZIONI MENU ─────────────────────────────────────── */
  'soluzioni-menu': [
    ['Trinacria', 'Portamenù A4 ad anelli in betulla', 'meccanismi-ad-anelli', ['compensato'], ['taglio-laser', 'incisione-laser'], { larghezza: '23 cm', altezza: '32 cm', spessore: '6 mm' }, ['ristorazione', 'aziendale'], 'b2b', 'Meccanismo a quattro anelli da 25 mm fissato su dorso rinforzato: le pagine si cambiano in pochi secondi senza attrezzi. È il modello che consigliamo a chi aggiorna il menù ogni settimana.', ['logo', 'colore', 'numero pagine'], true],
    ['Kalsa', 'Portamenù A4 a vite passante', 'meccanismi-a-vite', ['compensato', 'legno-massello'], ['taglio-laser', 'incisione-laser'], { larghezza: '23 cm', altezza: '32 cm', spessore: '10 mm' }, ['ristorazione'], 'b2b', 'Viti passanti in ottone che attraversano tutto il pacco pagine e si serrano a mano. Nessun meccanismo a vista, nessuna parte mobile che possa cedere: la scelta per chi cambia il menù due volte l\'anno.', ['logo', 'colore', 'finitura viti']],
    ['Aretusa', 'Portamenù A5 ad anelli', 'meccanismi-ad-anelli', ['compensato'], ['taglio-laser', 'incisione-laser'], { larghezza: '16 cm', altezza: '23 cm', spessore: '6 mm' }, ['ristorazione'], 'b2b', 'Formato ridotto per carta dei vini, dolci o cocktail. Sta in piedi da solo sul tavolo grazie al dorso più spesso e non ruba spazio al coperto.', ['logo', 'colore', 'numero pagine']],
    ['Ortigia', 'Portamenù A4 con dorso in pelle', 'formato-a4', ['compensato', 'pelle-vegetale'], ['taglio-laser', 'incisione-laser'], { larghezza: '23 cm', altezza: '32 cm', spessore: '12 mm' }, ['ristorazione', 'turismo'], 'b2b', 'Copertine in betulla e dorso flessibile in cuoio vegetale cucito a mano. Il legno dà rigidità alla presa, la pelle assorbe l\'apertura ripetuta senza segnarsi.', ['logo', 'colore pelle', 'incisione-laser']],
    ['Cefalù', 'Portamenù a pinza per fogli singoli', 'meccanismi-a-pinza', ['compensato', 'alluminio-anodizzato'], ['taglio-laser', 'incisione-laser'], { larghezza: '23 cm', altezza: '33 cm', spessore: '15 mm' }, ['ristorazione'], 'b2b', 'Pinza a molla in alluminio sul lato lungo: si solleva, si infila il foglio del giorno, si rilascia. Pensato per chi stampa il menù ogni mattina.', ['logo', 'colore', 'finitura pinza']],
    ['Erice', 'Portamenù A5 a vite', 'meccanismi-a-vite', ['compensato'], ['taglio-laser', 'incisione-laser'], { larghezza: '16 cm', altezza: '23 cm', spessore: '8 mm' }, ['ristorazione'], 'b2b', 'Versione compatta a viti passanti, fino a otto facciate. Ideale come carta dei dolci da lasciare sul tavolo a fine servizio.', ['logo', 'colore']],
    ['Marzamemi', 'Espositore da tavolo bifacciale', 'espositori-da-tavolo', ['compensato', 'plexiglass-colato'], ['taglio-laser', 'taglio-laser'], { larghezza: '12 cm', altezza: '18 cm', profondita: '8 cm' }, ['ristorazione'], 'b2b', 'Due tasche in plexiglass montate schiena contro schiena su base zavorrata: la promozione si legge da entrambi i lati del tavolo senza doverlo girare.', ['logo', 'formato tasca']],
    ['Vucciria', 'Espositore a leggio', 'espositori-da-tavolo', ['compensato'], ['taglio-laser', 'incisione-laser'], { larghezza: '21 cm', altezza: '26 cm', profondita: '14 cm' }, ['ristorazione', 'eventi'], 'b2b', 'Inclinazione a 20° calcolata per la lettura da seduti. Si smonta in tre pezzi piatti, quindi si immagazzina e si trasporta senza ingombro.', ['logo', 'colore', 'formato']],
    ['Ballarò', 'Porta QR da tavolo', 'menu-qr', ['compensato'], ['taglio-laser', 'incisione-laser'], { larghezza: '7 cm', altezza: '10 cm', spessore: '6 mm' }, ['ristorazione', 'tecnologia'], 'b2b', 'QR inciso direttamente nel legno, non stampato su adesivo: non si stacca, non si sbianca con i detergenti, non va sostituito ogni due mesi.', ['logo', 'QR', 'testo']],
    ['Salina', 'Cubo QR quadrifacciale', 'menu-qr', ['compensato'], ['taglio-laser', 'incisione-laser'], { lato: '8 cm', altezza: '8 cm' }, ['ristorazione', 'tecnologia'], 'b2b', 'Quattro facce incise: il codice resta leggibile da ogni posto al tavolo. Le facce possono portare QR diversi — menù, recensioni, wifi, social.', ['logo', 'QR per faccia', 'testo']],
    ['Vulcano', 'Tag NFC da tavolo', 'menu-nfc', ['compensato', 'alluminio-anodizzato'], ['taglio-laser', 'incisione-laser'], { diametro: '6 cm', spessore: '10 mm' }, ['ristorazione', 'tecnologia'], 'b2b', 'Chip NTAG213 annegato nel legno e coperto da un disco in alluminio inciso. Il cliente avvicina il telefono e apre il menù: nessuna app, nessuna inquadratura.', ['logo', 'URL', 'finitura']],
    ['Selinunte', 'Portamenù A4 in plexiglass', 'formato-a4', ['plexiglass-colato'], ['taglio-laser', 'taglio-laser', 'incisione-laser'], { larghezza: '22 cm', altezza: '31 cm', spessore: '5 mm' }, ['ristorazione'], 'b2b', 'Due lastre trasparenti a taglio lucido tenute da distanziali in acciaio. Si pulisce con un panno, regge il contatto con i disinfettanti e non trattiene odori.', ['logo inciso', 'colore lastre']],
    ['Segesta', 'Portamenù A5 in plexiglass', 'formato-a5', ['plexiglass-colato'], ['taglio-laser', 'taglio-laser', 'incisione-laser'], { larghezza: '15 cm', altezza: '22 cm', spessore: '5 mm' }, ['ristorazione'], 'b2b', 'Versione A5 della lastra trasparente, con base a T che la tiene in piedi. Adatta a carte brevi e liste cocktail.', ['logo inciso', 'colore base']],
    ['Mothia', 'Portamenù a tre ante', 'formati-personalizzati', ['compensato'], ['taglio-laser', 'incisione-laser'], { larghezza: '48 cm', altezza: '32 cm', spessore: '6 mm' }, ['ristorazione'], 'b2b', 'Si apre a libro su tre pannelli e mostra sei facciate in un colpo solo. Le cerniere in tessuto tecnico reggono l\'apertura ripetuta meglio di quelle metalliche.', ['logo', 'colore', 'numero ante']],
    ['Tindari', 'Portamenù formato lungo per lista vini', 'formati-personalizzati', ['compensato', 'legno-massello'], ['taglio-laser', 'incisione-laser'], { larghezza: '12 cm', altezza: '34 cm', spessore: '8 mm' }, ['ristorazione'], 'b2b', 'Proporzione stretta e alta, disegnata per liste lunghe con poche colonne. Sta in piedi accanto al calice senza occupare il coperto.', ['logo', 'colore', 'numero pagine']],
    ['Naxos', 'Portamenù a pinza con base', 'meccanismi-a-pinza', ['compensato', 'acciaio-inox'], ['taglio-laser'], { larghezza: '16 cm', altezza: '24 cm', profondita: '10 cm' }, ['ristorazione'], 'b2b', 'Pinza in acciaio su base pesante: resta in piedi anche con un foglio singolo e non si rovescia se qualcuno lo urta passando.', ['logo', 'finitura base']],
    ['Taormina', 'Portamenù A4 con copertina incisa', 'formato-a4', ['compensato'], ['taglio-laser', 'incisione-laser'], { larghezza: '23 cm', altezza: '32 cm', spessore: '6 mm' }, ['ristorazione', 'turismo'], 'b2b', 'La copertina è incisa a tutta superficie: pattern, illustrazione o marchio a grande scala. È il modello su cui lavoriamo quando il portamenù deve funzionare anche come immagine del locale.', ['grafica copertina', 'logo', 'colore'], true],
    ['Noto', 'Portacarta dei vini ad anelli', 'meccanismi-ad-anelli', ['legno-massello', 'compensato'], ['taglio-laser', 'incisione-laser'], { larghezza: '24 cm', altezza: '33 cm', spessore: '14 mm' }, ['ristorazione'], 'b2b', 'Copertine in massello da 10 mm, più pesanti e più solide del modello standard: la carta dei vini si consulta in piedi, spesso con una mano sola.', ['logo', 'essenza', 'numero pagine']],
    ['Ragusa', 'Espositore da banco per menu del giorno', 'espositori-da-tavolo', ['compensato', 'plexiglass-colato'], ['taglio-laser', 'taglio-laser'], { larghezza: '24 cm', altezza: '32 cm', profondita: '12 cm' }, ['ristorazione'], 'b2b', 'Tasca A4 verticale su base larga, pensata per il bancone all\'ingresso. Il foglio si sfila dall\'alto senza smontare nulla.', ['logo', 'formato tasca']],
    ['Modica', 'Porta QR a bandiera da parete', 'menu-qr', ['compensato', 'alluminio-anodizzato'], ['taglio-laser', 'incisione-laser'], { larghezza: '10 cm', altezza: '14 cm', sporgenza: '12 cm' }, ['ristorazione', 'tecnologia'], 'b2b', 'Montato perpendicolare al muro, si vede da tutto il corridoio. Utile all\'ingresso o vicino alla cassa, dove un cartello piatto passerebbe inosservato.', ['logo', 'QR', 'staffa']],
    ['Favignana', 'Portamenù A5 con elastico', 'formato-a5', ['compensato'], ['taglio-laser', 'incisione-laser'], { larghezza: '16 cm', altezza: '23 cm', spessore: '4 mm' }, ['ristorazione', 'turismo'], 'b2b', 'Due pannelli e un elastico colorato che trattiene i fogli. Il modello più leggero ed economico del catalogo, adatto alle grandi quantità e ai dehors.', ['logo', 'colore elastico']],
    ['Lipari', 'Menu NFC in alluminio', 'menu-nfc', ['alluminio-anodizzato'], ['marcatura-metalli', 'marcatura-metalli', 'taglio-laser'], { larghezza: '5,4 cm', altezza: '8,6 cm', spessore: '1 mm' }, ['ristorazione', 'tecnologia'], 'b2b', 'Formato carta di credito in alluminio anodizzato con marcatura MOPA. Resiste al lavaggio e all\'usura del tavolo molto più di qualsiasi supporto stampato.', ['logo', 'URL', 'colore anodizzazione']],
    ['Pantelleria', 'Portamenù XL per lavagna del giorno', 'formati-personalizzati', ['compensato', 'mdf'], ['taglio-laser'], { larghezza: '40 cm', altezza: '60 cm', spessore: '16 mm' }, ['ristorazione'], 'b2b', 'Pannello verniciato a lavagna con cornice in betulla, da parete o su cavalletto. Si scrive a gesso liquido e si cancella con un panno umido.', ['logo', 'formato', 'colore cornice']],
    ['Ustica', 'Portamenù A4 a vite con angoli in metallo', 'meccanismi-a-vite', ['compensato', 'alluminio-anodizzato'], ['taglio-laser', 'incisione-laser'], { larghezza: '23 cm', altezza: '32 cm', spessore: '12 mm' }, ['ristorazione', 'turismo'], 'b2b', 'Angoli in alluminio a protezione degli spigoli, il punto in cui i portamenù si rovinano per primi. Consigliato dove il ricambio è alto e i pezzi vengono maneggiati molto.', ['logo', 'finitura angoli', 'colore']]
  ],

  /* ── TAVOLA & CUCINA ────────────────────────────────────── */
  'tavola-cucina': [
    ['Zagara', 'Apribottiglie da banco in acciaio e legno', 'apribottiglie', ['legno-massello', 'acciaio-inox'], ['taglio-laser', 'incisione-laser'], { larghezza: '8 cm', altezza: '20 cm', spessore: '20 mm' }, ['ristorazione', 'regali'], 'both', 'Lama in acciaio inox fissata su corpo in massello, da avvitare al bancone o alla parete. Il tappo cade nel raccoglitore sottostante invece che per terra.', ['logo', 'essenza', 'incisione-laser'], true],
    ['Agave', 'Apribottiglie tascabile inciso', 'apribottiglie', ['acciaio-inox'], ['marcatura-metalli', 'marcatura-metalli'], { larghezza: '2,5 cm', altezza: '7 cm', spessore: '2 mm' }, ['gadget', 'aziendale'], 'both', 'Acciaio inox da 2 mm marcato a laser MOPA. La marcatura è ossidazione del metallo: non si consuma in tasca né in lavastoviglie.', ['logo', 'testo', 'colore marcatura']],
    ['Ficodindia', 'Segnatavolo numerato bifacciale', 'segnatavoli', ['compensato'], ['taglio-laser', 'incisione-laser'], { larghezza: '8 cm', altezza: '12 cm', base: '6 cm' }, ['ristorazione'], 'b2b', 'Numero inciso su entrambe le facce e base a incastro removibile. Il personale legge il tavolo da qualsiasi direzione senza avvicinarsi.', ['numeri', 'logo', 'colore']],
    ['Gelso', 'Segnatavolo a cubo', 'segnatavoli', ['compensato', 'legno-massello'], ['taglio-laser', 'incisione-laser'], { lato: '7 cm' }, ['ristorazione'], 'b2b', 'Cubo pieno con numero inciso su quattro facce. Pesa abbastanza da non spostarsi quando si apparecchia.', ['numeri', 'logo', 'essenza']],
    ['Carrubo', 'Segnaposto sagomato in betulla', 'segnaposto', ['compensato'], ['taglio-laser', 'incisione-laser', 'taglio-laser'], { larghezza: '9 cm', altezza: '5 cm', spessore: '3 mm' }, ['wedding', 'eventi'], 'both', 'Sagoma tagliata e nome inciso singolarmente. Ogni pezzo è diverso perché ogni nome è diverso: è il dettaglio che gli ospiti portano a casa.', ['nome', 'sagoma', 'font']],
    ['Mandorlo', 'Segnaposto con portafoto', 'segnaposto', ['compensato'], ['taglio-laser', 'incisione-laser'], { larghezza: '10 cm', altezza: '7 cm', spessore: '6 mm' }, ['wedding', 'eventi'], 'both', 'Base con fessura che regge sia il cartoncino del nome sia una polaroid. Dopo il servizio resta un piccolo portafoto da scrivania.', ['nome', 'incisione-laser', 'colore']],
    ['Bergamotto', 'Poggia-posate a onda', 'poggia-posate', ['legno-massello'], ['taglio-laser', 'taglio-laser'], { larghezza: '10 cm', profondita: '3 cm', altezza: '2 cm' }, ['ristorazione', 'casa'], 'both', 'Profilo curvo che tiene sollevate lama e rebbi dalla tovaglia. Finitura a olio certificato per contatto alimentare, lavabile a mano.', ['essenza', 'incisione-laser', 'finitura']],
    ['Limone', 'Poggia-bacchette in essenze accostate', 'poggia-bacchette', ['legno-massello'], ['taglio-laser', 'taglio-laser'], { larghezza: '7 cm', profondita: '2 cm', altezza: '1,5 cm' }, ['ristorazione'], 'b2b', 'Due essenze incollate a contrasto e poi sagomate: la venatura cambia colore a metà pezzo. Finitura a olio idoneo al contatto alimentare.', ['essenze', 'incisione-laser']],
    ['Ulivo', 'Porta conto a pinza', 'porta-conto', ['compensato', 'alluminio-anodizzato'], ['taglio-laser', 'incisione-laser'], { larghezza: '12 cm', altezza: '18 cm', spessore: '10 mm' }, ['ristorazione'], 'b2b', 'Pinza superiore che tiene scontrino e banconote insieme, anche quando il cameriere lo porta in verticale su un vassoio pieno.', ['logo', 'colore', 'finitura pinza']],
    ['Melograno', 'Porta conto con vano scontrino', 'porta-conto', ['compensato'], ['taglio-laser', 'incisione-laser'], { larghezza: '13 cm', altezza: '19 cm', spessore: '15 mm' }, ['ristorazione'], 'b2b', 'Si apre a libro: lo scontrino nella tasca interna, le banconote sotto l\'elastico. Chiuso non lascia vedere l\'importo agli altri tavoli.', ['logo', 'colore interno', 'incisione-laser']],
    ['Cappero', 'Porta resto con vaschetta', 'porta-resto', ['compensato'], ['taglio-laser'], { larghezza: '14 cm', profondita: '10 cm', altezza: '3 cm' }, ['ristorazione'], 'b2b', 'Vaschetta con fondo ribassato e bordo alto: le monete non scivolano fuori quando il vassoio si inclina.', ['logo', 'colore', 'incisione fondo']],
    ['Mirto', 'Portatovaglioli da banco a doppia estrazione', 'portatovaglioli', ['compensato'], ['taglio-laser', 'incisione-laser'], { larghezza: '16 cm', profondita: '12 cm', altezza: '14 cm' }, ['ristorazione'], 'b2b', 'Due bocche di estrazione su lati opposti: due clienti servono se stessi contemporaneamente senza incrociarsi sul bancone.', ['logo', 'colore', 'formato tovagliolo'], true],
    ['Origano', 'Portatovaglioli da tavolo', 'portatovaglioli', ['compensato'], ['taglio-laser', 'incisione-laser'], { larghezza: '13 cm', profondita: '7 cm', altezza: '10 cm' }, ['ristorazione', 'casa'], 'both', 'Formato compatto per il coperto, con peso sufficiente a non ribaltarsi quando si estrae l\'ultimo tovagliolo.', ['logo', 'colore', 'incisione-laser']],
    ['Timo', 'Porta zucchero a due scomparti', 'porta-zucchero', ['compensato'], ['taglio-laser'], { larghezza: '12 cm', profondita: '7 cm', altezza: '5 cm' }, ['ristorazione'], 'b2b', 'Due vani separati per zucchero e dolcificante, con divisorio rimovibile per la pulizia di fine turno.', ['logo', 'colore', 'divisori']],
    ['Rosmarino', 'Menage completo tre posti', 'menage', ['compensato', 'legno-massello'], ['taglio-laser', 'incisione-laser'], { larghezza: '18 cm', profondita: '8 cm', altezza: '12 cm' }, ['ristorazione'], 'b2b', 'Tre alloggiamenti sagomati su misura delle ampolle effettivamente in uso nel locale, più maniglia centrale per spostarlo con una mano.', ['logo', 'misura alloggiamenti', 'essenza']],
    ['Alloro', 'Menage compatto due posti', 'menage', ['compensato'], ['taglio-laser'], { larghezza: '13 cm', profondita: '7 cm', altezza: '10 cm' }, ['ristorazione'], 'b2b', 'Versione ridotta per tavoli piccoli: olio e aceto, o sale e pepe. Fondo antiscivolo in sughero.', ['logo', 'misura alloggiamenti']],
    ['Sommacco', 'Sottobicchieri set da sei', 'sottobicchieri', ['compensato', 'legno-massello'], ['taglio-laser', 'incisione-laser'], { diametro: '9,5 cm', spessore: '4 mm' }, ['ristorazione', 'regali', 'casa'], 'both', 'Sei pezzi con incisioni diverse dello stesso tema, forniti in astuccio a incastro. Funziona bene come regalo aziendale sotto la soglia dei venti euro.', ['incisione-laser', 'logo', 'astuccio']],
    ['Lentisco', 'Sottobicchiere singolo inciso', 'sottobicchieri', ['compensato'], ['taglio-laser', 'incisione-laser'], { diametro: '9,5 cm', spessore: '4 mm' }, ['ristorazione', 'gadget'], 'b2b', 'Pezzo singolo per grandi quantità: il costo unitario scende sensibilmente sopra i duecento pezzi, mantenendo l\'incisione a piena risoluzione.', ['logo', 'forma', 'incisione-laser']],
    ['Ginestra', 'Vassoio da servizio rettangolare', 'vassoi', ['legno-massello'], ['taglio-laser', 'incisione-laser'], { larghezza: '40 cm', profondita: '28 cm', altezza: '3 cm' }, ['ristorazione'], 'b2b', 'Massello da 15 mm con bordo rialzato e fondo trattato a olio alimentare. Regge il peso di un servizio completo senza flettere al centro.', ['logo', 'essenza', 'misura']],
    ['Corbezzolo', 'Vassoio da colazione con manici', 'vassoi', ['compensato', 'legno-massello'], ['taglio-laser', 'taglio-laser'], { larghezza: '45 cm', profondita: '30 cm', altezza: '5 cm' }, ['turismo', 'casa'], 'both', 'Manici ricavati nel pieno del pannello, senza parti riportate che possano staccarsi. Pensato per il servizio in camera di B&B e case vacanza.', ['logo', 'incisione-laser', 'finitura']],
    ['Pistacchio', 'Tagliere da servizio in massello', 'taglieri', ['legno-massello'], ['taglio-laser', 'incisione-laser'], { larghezza: '35 cm', profondita: '20 cm', spessore: '20 mm' }, ['ristorazione', 'regali'], 'both', 'Faggio o frassino da 20 mm, finitura a olio di lino cotto certificato. L\'incisione è sul lato di presentazione: il lato di taglio resta liscio.', ['logo', 'essenza', 'misura'], true],
    ['Nocciolo', 'Tagliere sagomato con scanalatura', 'taglieri', ['legno-massello'], ['taglio-laser', 'taglio-laser'], { larghezza: '38 cm', profondita: '24 cm', spessore: '20 mm' }, ['ristorazione', 'casa'], 'both', 'Canalina perimetrale che raccoglie i liquidi di taglio e impedisce che finiscano sul tavolo. Utile per carni e formaggi a pasta molle.', ['logo', 'essenza', 'sagoma']],
    ['Sorbo', 'Tagliere da aperitivo con vaschette', 'taglieri', ['legno-massello', 'plexiglass-colato'], ['taglio-laser', 'taglio-laser'], { larghezza: '45 cm', profondita: '20 cm', spessore: '25 mm' }, ['ristorazione'], 'b2b', 'Tre incavi che ospitano vaschette rimovibili per salse e olive, così il tagliere si lava senza svuotarlo prima.', ['logo', 'numero vaschette', 'essenza']],
    ['Papiro', 'Poggia-posate a barra per tavolo lungo', 'poggia-posate', ['legno-massello'], ['taglio-laser', 'taglio-laser'], { larghezza: '30 cm', profondita: '4 cm', altezza: '2 cm' }, ['ristorazione', 'eventi'], 'b2b', 'Barra unica con più sedi ricavate: serve un\'intera fila di coperti sui tavoli imperiali, dove i poggia-posate singoli si spostano continuamente.', ['numero sedi', 'essenza', 'incisione-laser']],
    ['Canna', 'Segnatavolo a bandierina', 'segnatavoli', ['compensato', 'alluminio-anodizzato'], ['taglio-laser', 'incisione-laser'], { larghezza: '6 cm', altezza: '22 cm' }, ['ristorazione', 'eventi'], 'b2b', 'Numero montato su asta sottile: si vede sopra bicchieri e bottiglie, che è esattamente il problema dei segnatavoli bassi a sala piena.', ['numeri', 'altezza asta', 'logo']],
    ['Giunco', 'Porta conto verticale da banco', 'porta-conto', ['compensato'], ['taglio-laser'], { larghezza: '10 cm', altezza: '15 cm', profondita: '8 cm' }, ['ristorazione'], 'b2b', 'Raccoglitore da cassa con più scomparti verticali: i conti aperti restano ordinati e visibili invece di accumularsi in pila.', ['logo', 'numero scomparti', 'colore']]
  ],

  /* ── WOOD ART & DESIGN ──────────────────────────────────── */
  'wood-art-design': [
    ['Tufo', 'Cassetta a incastro personalizzabile', 'cassette', ['compensato', 'compensato'], ['taglio-laser', 'taglio-laser', 'incisione-laser'], { larghezza: '30 cm', profondita: '20 cm', altezza: '15 cm' }, ['regali', 'aziendale'], 'both', 'Incastri a coda di rondine tagliati al laser: si monta a pressione, senza colla né viti, e si smonta piatta per la spedizione.', ['incisione-laser', 'misura', 'finitura'], true],
    ['Basalto', 'Cassetta con coperchio scorrevole', 'cassette', ['compensato'], ['taglio-laser', 'taglio-laser'], { larghezza: '25 cm', profondita: '18 cm', altezza: '12 cm' }, ['regali', 'aziendale'], 'both', 'Coperchio che scorre in due scanalature laterali, senza cerniere che si allentino nel tempo. Apertura silenziosa, chiusura a battuta.', ['incisione coperchio', 'misura', 'finitura']],
    ['Pomice', 'Cofanetto portagioie con magnete', 'cofanetti', ['compensato', 'tessuto'], ['taglio-laser', 'incisione-laser'], { larghezza: '18 cm', profondita: '13 cm', altezza: '7 cm' }, ['regali', 'wedding'], 'b2c', 'Chiusura a magneti annegati nel legno e interno foderato in feltro. Il coperchio si chiude da solo nell\'ultimo centimetro.', ['incisione-laser', 'colore feltro', 'misura']],
    ['Ossidiana', 'Cofanetto per bottiglia singola', 'cofanetti', ['compensato'], ['taglio-laser', 'incisione-laser'], { larghezza: '11 cm', profondita: '11 cm', altezza: '35 cm' }, ['regali', 'aziendale'], 'both', 'Sagomato internamente sulla bottiglia effettiva, non su una misura standard: il vetro non balla durante il trasporto.', ['incisione-laser', 'misura bottiglia', 'finitura']],
    ['Salgemma', 'Cofanetto degustazione tre bottiglie', 'cofanetti', ['compensato', 'compensato'], ['taglio-laser', 'taglio-laser'], { larghezza: '32 cm', profondita: '12 cm', altezza: '35 cm' }, ['aziendale', 'regali'], 'b2b', 'Tre alloggiamenti separati da divisori a incastro rimovibili, per spedire una selezione senza imballaggio aggiuntivo.', ['incisione-laser', 'numero posti', 'finitura']],
    ['Terracotta', 'Porta biglietti da visita da scrivania', 'porta-biglietti', ['legno-massello'], ['taglio-laser', 'incisione-laser'], { larghezza: '10 cm', profondita: '7 cm', altezza: '4 cm' }, ['aziendale'], 'both', 'Massello pieno con sede inclinata: i biglietti restano leggibili da chi è seduto davanti alla scrivania, non solo da chi la occupa.', ['logo', 'essenza', 'incisione-laser']],
    ['Cotto', 'Porta biglietti da visita tascabile', 'porta-biglietti', ['compensato', 'alluminio-anodizzato'], ['taglio-laser'], { larghezza: '9,5 cm', profondita: '6 cm', spessore: '12 mm' }, ['aziendale', 'regali'], 'both', 'Guscio in betulla con anima in alluminio che protegge i biglietti dalla piega in tasca. Apertura a scatto.', ['logo', 'incisione-laser', 'finitura']],
    ['Alabastro', 'Espositore a gradoni tre livelli', 'espositori', ['compensato', 'mdf'], ['taglio-laser'], { larghezza: '40 cm', profondita: '25 cm', altezza: '25 cm' }, ['ristorazione', 'eventi'], 'b2b', 'Tre piani sfalsati che rendono visibile l\'intera esposizione dal fronte, senza che la prima fila copra le altre.', ['logo', 'numero livelli', 'colore']],
    ['Quarzo', 'Espositore verticale a colonna', 'espositori', ['compensato'], ['taglio-laser', 'taglio-laser'], { larghezza: '20 cm', profondita: '20 cm', altezza: '90 cm' }, ['eventi', 'aziendale'], 'b2b', 'Colonna smontabile in cinque elementi piatti, montaggio senza attrezzi in meno di due minuti. Pensato per gli allestimenti che viaggiano.', ['logo', 'altezza', 'colore']],
    ['Ambra', 'Biglietto da visita NFC in legno', 'creazioni-nfc', ['compensato'], ['taglio-laser', 'incisione-laser'], { larghezza: '8,6 cm', altezza: '5,4 cm', spessore: '1,5 mm' }, ['aziendale', 'tecnologia'], 'both', 'Impiallacciato sottile con chip NFC integrato: si avvicina al telefono e apre il contatto, il sito o il profilo social. Dati riprogrammabili senza rifare il biglietto.', ['logo', 'URL', 'incisione-laser'], true],
    ['Corallo', 'Placca NFC da banco per recensioni', 'creazioni-nfc', ['compensato', 'alluminio-anodizzato'], ['taglio-laser', 'incisione-laser'], { larghezza: '9 cm', altezza: '12 cm', spessore: '15 mm' }, ['ristorazione', 'tecnologia'], 'b2b', 'Base inclinata da bancone con chip NFC e QR di riserva incisi. Il cliente lascia la recensione prima di uscire, non tre giorni dopo.', ['logo', 'URL', 'testo']],
    ['Madreperla', 'Targa decorativa a strati sovrapposti', 'targhe-decorative', ['compensato', 'mdf'], ['taglio-laser', 'taglio-laser'], { larghezza: '30 cm', altezza: '30 cm', spessore: '18 mm' }, ['casa', 'regali'], 'b2c', 'Tre o più livelli tagliati separatamente e sovrapposti con distanziali: l\'ombra fra gli strati dà profondità reale, non disegnata.', ['grafica', 'numero strati', 'colori']],
    ['Marmo', 'Targa decorativa con retro illuminato', 'targhe-decorative', ['compensato', 'plexiglass-colato'], ['taglio-laser', 'taglio-laser'], { larghezza: '35 cm', altezza: '25 cm', spessore: '30 mm' }, ['casa', 'ristorazione'], 'both', 'Fronte traforato in betulla su diffusore in acrilico opalino con LED a bassa tensione: di giorno è una targa, di sera una fonte di luce.', ['grafica', 'temperatura LED', 'misura']],
    ['Calcare', 'Segnaletica direzionale a bandiera', 'segnaletica', ['compensato', 'alluminio-anodizzato'], ['taglio-laser', 'incisione-laser'], { larghezza: '25 cm', altezza: '10 cm', sporgenza: '20 cm' }, ['turismo', 'ristorazione'], 'b2b', 'Montaggio perpendicolare alla parete con staffa in alluminio, leggibile lungo tutto il corridoio. Componibile su più livelli per direzioni multiple.', ['testo', 'frecce', 'finitura']],
    ['Faro', 'Tableau de mariage a pannelli', 'matrimoni', ['compensato'], ['taglio-laser', 'incisione-laser'], { larghezza: '60 cm', altezza: '80 cm', spessore: '6 mm' }, ['wedding', 'eventi'], 'b2c', 'Pannello principale più tessere removibili per tavolo: se la disposizione cambia all\'ultimo, si sostituisce la singola tessera invece dell\'intero tableau.', ['nomi', 'grafica', 'misura']],
    ['Tonnara', 'Guestbook a tessere componibili', 'matrimoni', ['compensato'], ['taglio-laser', 'taglio-laser', 'incisione-laser'], { larghezza: '40 cm', altezza: '40 cm', spessore: '4 mm' }, ['wedding'], 'b2c', 'Ogni ospite firma una tessera che si incastra nel telaio: alla fine della serata il guestbook è un quadro completo, non un libro chiuso in un cassetto.', ['numero tessere', 'grafica', 'incisione-laser']],
    ['Cala', 'Cornice ricordo per evento', 'eventi-speciali', ['compensato'], ['taglio-laser', 'incisione-laser'], { larghezza: '25 cm', altezza: '20 cm', spessore: '12 mm' }, ['eventi', 'wedding'], 'both', 'Cornice con incisione della data e del luogo, fornita con passe-partout tagliato su misura della foto.', ['testo', 'formato foto', 'finitura']],
    ['Scoglio', 'Porta confetti componibile', 'eventi-speciali', ['compensato'], ['taglio-laser', 'taglio-laser', 'incisione-laser'], { larghezza: '7 cm', profondita: '7 cm', altezza: '8 cm' }, ['wedding', 'eventi'], 'b2c', 'Si spedisce piatto e si monta a incastro sul posto: cento bomboniere occupano una scatola invece di un bagagliaio.', ['incisione-laser', 'sagoma', 'colore']]
  ],

  /* ── OGGETTISTICA ───────────────────────────────────────── */
  'oggettistica': [
    ['Sestante', 'Portapenne da scrivania a scomparti', 'scrivania', ['compensato', 'legno-massello'], ['taglio-laser', 'incisione-laser'], { larghezza: '12 cm', profondita: '8 cm', altezza: '10 cm' }, ['aziendale', 'casa'], 'both', 'Tre scomparti di profondità diversa: penne, forbici e post-it restano separati invece di finire tutti nello stesso vano.', ['logo', 'essenza', 'incisione-laser']],
    ['Chiglia', 'Sottomano da scrivania in pelle e legno', 'scrivania', ['pelle-vegetale', 'compensato'], ['taglio-laser', 'incisione-laser'], { larghezza: '60 cm', profondita: '40 cm', spessore: '4 mm' }, ['aziendale'], 'both', 'Cuoio vegetale con bordo in betulla incisa. La pelle si scurisce con l\'uso lungo le zone di appoggio, ed è il motivo per cui la scegliamo.', ['logo', 'colore pelle', 'misura']],
    ['Timone', 'Porta smartphone da scrivania', 'scrivania', ['legno-massello'], ['taglio-laser', 'taglio-laser'], { larghezza: '8 cm', profondita: '9 cm', altezza: '7 cm' }, ['aziendale', 'gadget'], 'both', 'Doppia sede, verticale e orizzontale, con passaggio per il cavo di ricarica ricavato nel pieno del legno.', ['logo', 'essenza', 'incisione-laser']],
    ['Prua', 'Svuotatasche rettangolare', 'svuotatasche', ['legno-massello'], ['taglio-laser', 'incisione-laser'], { larghezza: '18 cm', profondita: '12 cm', altezza: '3 cm' }, ['casa', 'regali'], 'b2c', 'Massello scavato in un pezzo unico, senza giunzioni sul fondo dove si accumulerebbe polvere. Finitura a cera.', ['incisione-laser', 'essenza', 'misura']],
    ['Vela', 'Svuotatasche con vano portachiavi', 'svuotatasche', ['compensato', 'legno-massello'], ['taglio-laser'], { larghezza: '22 cm', profondita: '14 cm', altezza: '5 cm' }, ['casa', 'regali'], 'b2c', 'Vano principale più sede stretta per le chiavi, così non finiscono sotto il resto e si trovano al buio.', ['incisione-laser', 'colore', 'misura']],
    ['Randa', 'Fermalibri geometrico a coppia', 'fermalibri', ['compensato', 'acciaio-inox'], ['taglio-laser', 'taglio-laser'], { larghezza: '12 cm', profondita: '12 cm', altezza: '16 cm' }, ['casa', 'regali'], 'b2c', 'Anima in acciaio da 2 mm rivestita in betulla: pesa il necessario per reggere una fila di volumi rilegati, non solo tascabili.', ['incisione-laser', 'colore', 'altezza']],
    ['Boma', 'Fermalibri sagomato singolo', 'fermalibri', ['compensato'], ['taglio-laser', 'taglio-laser'], { larghezza: '10 cm', profondita: '10 cm', altezza: '18 cm' }, ['casa'], 'b2c', 'Pezzo singolo con sagoma personalizzabile su richiesta, dal profilo geometrico alla silhouette figurativa.', ['sagoma', 'colore', 'incisione-laser']],
    ['Ancora', 'Organizer da cassetto modulare', 'organizer', ['compensato'], ['taglio-laser', 'taglio-laser'], { larghezza: '30 cm', profondita: '20 cm', altezza: '5 cm' }, ['casa', 'aziendale'], 'both', 'Divisori a incastro riposizionabili: la griglia si adatta al cassetto esistente invece di obbligare a scegliere fra misure standard.', ['misura cassetto', 'numero divisori']],
    ['Sartia', 'Organizer porta cavi da scrivania', 'organizer', ['compensato', 'plexiglass-colato'], ['taglio-laser', 'prototipazione'], { larghezza: '15 cm', profondita: '6 cm', altezza: '4 cm' }, ['aziendale', 'casa'], 'both', 'Fessure sagomate che trattengono i cavi per attrito: si sfilano tirando, non si riavvolgono da soli dietro la scrivania.', ['numero fessure', 'colore', 'incisione-laser']],
    ['Deriva', 'Scultura da tavolo a strati', 'decorativi', ['compensato', 'mdf'], ['taglio-laser', 'taglio-laser'], { larghezza: '20 cm', profondita: '10 cm', altezza: '25 cm' }, ['casa', 'regali'], 'b2c', 'Curve di livello tagliate una per una e impilate: da lontano è una forma piena, da vicino si legge ogni strato.', ['soggetto', 'numero strati', 'finitura']],
    ['Rotta', 'Mappa incisa da parete', 'decorativi', ['compensato'], ['taglio-laser', 'incisione-laser'], { larghezza: '60 cm', altezza: '40 cm', spessore: '6 mm' }, ['casa', 'turismo', 'turismo'], 'both', 'Cartografia incisa a profondità variabile: la costa è più profonda dell\'entroterra e la differenza si legge con la luce radente.', ['area geografica', 'misura', 'punti di interesse']],
    ['Scia', 'Portafoto a incastro', 'decorativi', ['compensato'], ['taglio-laser', 'taglio-laser'], { larghezza: '15 cm', altezza: '20 cm', spessore: '4 mm' }, ['casa', 'regali'], 'b2c', 'Tre pezzi che si montano senza colla e si smontano piatti. Adatto alla spedizione in busta imbottita.', ['formato foto', 'incisione-laser', 'colore']]
  ],

  /* ── TARGHE & INSEGNE ───────────────────────────────────── */
  'targhe-insegne': [
    ['Alba', 'Targa di ingresso ovale in betulla', 'targhe-ingresso', ['compensato'], ['taglio-laser', 'incisione-laser'], { larghezza: '25 cm', altezza: '15 cm', spessore: '9 mm' }, ['turismo', 'casa'], 'both', 'Ovale con incisione profonda e finitura protettiva per esterni riparati. È il formato che B&B e case vacanza chiedono più spesso per la porta di ingresso.', ['testo', 'grafica', 'finitura'], true],
    ['Aurora', 'Targa di ingresso rettangolare a due strati', 'targhe-ingresso', ['compensato', 'mdf'], ['taglio-laser', 'taglio-laser'], { larghezza: '30 cm', altezza: '12 cm', spessore: '15 mm' }, ['turismo', 'aziendale'], 'b2b', 'Fondo verniciato e lettere tagliate a parte, sollevate su distanziali: le lettere proiettano ombra e restano leggibili anche in controluce.', ['testo', 'colori', 'misura']],
    ['Meriggio', 'Numero civico sagomato in alluminio', 'numeri-civici', ['alluminio-anodizzato'], ['marcatura-metalli', 'taglio-laser', 'marcatura-metalli'], { larghezza: '12 cm', altezza: '18 cm', spessore: '2 mm' }, ['casa'], 'b2c', 'Alluminio da 2 mm tagliato a sagoma, resistente a pioggia e sole senza manutenzione. Fissaggio a distanziali o adesivo strutturale.', ['numero', 'font', 'finitura']],
    ['Tramonto', 'Numero civico retroilluminato', 'numeri-civici', ['plexiglass-colato', 'alluminio-anodizzato'], ['taglio-laser', 'taglio-laser'], { larghezza: '15 cm', altezza: '22 cm', spessore: '30 mm' }, ['casa'], 'b2c', 'Numero in acrilico opalino su cassonetto in alluminio con LED a 12 V. Si accende al tramonto con sensore crepuscolare incluso.', ['numero', 'font', 'temperatura luce']],
    ['Zenit', 'Insegna da parete per locale', 'insegne-locale', ['compensato', 'mdf'], ['taglio-laser', 'taglio-laser'], { larghezza: '80 cm', altezza: '30 cm', spessore: '20 mm' }, ['ristorazione', 'aziendale'], 'b2b', 'Lettere e marchio tagliati e montati su pannello di fondo. Le proporzioni si ricalcolano sul logo reale, non si adatta il logo alla targa.', ['logo', 'misura', 'colori'], true],
    ['Nadir', 'Insegna a bandiera bifacciale', 'insegne-locale', ['compensato', 'alluminio-anodizzato'], ['taglio-laser', 'incisione-laser'], { larghezza: '40 cm', altezza: '30 cm', sporgenza: '45 cm' }, ['ristorazione', 'turismo'], 'b2b', 'Due facce identiche su staffa in alluminio: si legge da entrambi i sensi di marcia della strada, che è il motivo per cui esistono le insegne a bandiera.', ['logo', 'misura', 'staffa']],
    ['Eclissi', 'Insegna retroilluminata in acrilico', 'insegne-locale', ['plexiglass-colato', 'alluminio-anodizzato'], ['taglio-laser', 'taglio-laser'], { larghezza: '60 cm', altezza: '25 cm', spessore: '50 mm' }, ['ristorazione', 'aziendale'], 'b2b', 'Fronte in acrilico opalino su cassonetto in alluminio, LED a diffusione laterale. Nessun punto luce visibile sulla superficie.', ['logo', 'misura', 'temperatura luce']],
    ['Solstizio', 'Set segnaletica servizi igienici', 'segnaletica-servizio', ['compensato', 'plexiglass-colato'], ['taglio-laser', 'incisione-laser', 'taglio-laser'], { larghezza: '12 cm', altezza: '12 cm', spessore: '5 mm' }, ['ristorazione', 'turismo'], 'b2b', 'Pittogrammi incisi con contrasto sufficiente alla lettura rapida in corridoio. Fornito in set coordinato, non come pezzi singoli.', ['pittogrammi', 'testo', 'materiale']],
    ['Equinozio', 'Cartello orari di apertura', 'segnaletica-servizio', ['compensato'], ['taglio-laser', 'incisione-laser'], { larghezza: '20 cm', altezza: '30 cm', spessore: '6 mm' }, ['ristorazione', 'turismo'], 'b2b', 'Griglia oraria incisa con righe sostituibili a inserto: se cambia il turno di chiusura non si rifà tutto il cartello.', ['orari', 'logo', 'lingua']],
    ['Plenilunio', 'Freccia direzionale da parete', 'direzionali', ['compensato', 'alluminio-anodizzato'], ['taglio-laser', 'incisione-laser'], { larghezza: '35 cm', altezza: '10 cm', spessore: '9 mm' }, ['turismo', 'eventi'], 'b2b', 'Modulo componibile: più frecce si allineano sulla stessa staffa verticale per indicare direzioni diverse dallo stesso punto.', ['testo', 'direzione', 'finitura']],
    ['Novilunio', 'Totem direzionale da terra', 'direzionali', ['compensato', 'mdf'], ['taglio-laser'], { larghezza: '35 cm', profondita: '35 cm', altezza: '150 cm' }, ['eventi', 'turismo'], 'b2b', 'Base zavorrata e pannelli intercambiabili: lo stesso totem serve eventi diversi cambiando solo le facce.', ['contenuti', 'altezza', 'colori']],
    ['Crepuscolo', 'Targa numero camera con appendino', 'targhe-camere', ['compensato'], ['taglio-laser', 'incisione-laser'], { larghezza: '10 cm', altezza: '14 cm', spessore: '9 mm' }, ['turismo'], 'b2b', 'Numero camera più gancio integrato per il cartellino "non disturbare", ricavato nello stesso pezzo invece che aggiunto dopo.', ['numero', 'grafica', 'finitura']],
    ['Zefiro', 'Set targhe camere per struttura ricettiva', 'targhe-camere', ['compensato', 'alluminio-anodizzato'], ['taglio-laser', 'incisione-laser'], { larghezza: '12 cm', altezza: '12 cm', spessore: '10 mm' }, ['turismo'], 'b2b', 'Serie coordinata per l\'intera struttura, con numerazione progressiva e possibilità di nomi al posto dei numeri. Sconto a partire da otto camere.', ['numerazione', 'grafica', 'materiale']],
    ['Borea', 'Targa professionale in acciaio inox', 'targhe-metallo', ['acciaio-inox'], ['marcatura-metalli', 'marcatura-metalli', 'taglio-laser'], { larghezza: '30 cm', altezza: '20 cm', spessore: '1,5 mm' }, ['aziendale'], 'b2b', 'Inox spazzolato con marcatura MOPA: nero pieno su acciaio, senza inchiostro. È la targa da studio professionale che regge vent\'anni all\'esterno.', ['testo', 'logo', 'finitura']]
  ],

  /* ── GADGET ─────────────────────────────────────────────── */
  'gadget': [
    ['Libeccio', 'Portachiavi sagomato in betulla', 'portachiavi', ['compensato'], ['taglio-laser', 'taglio-laser', 'incisione-laser'], { larghezza: '4 cm', altezza: '6 cm', spessore: '4 mm' }, ['gadget', 'turismo', 'turismo'], 'both', 'Sagoma libera con incisione fronte-retro e anello in acciaio. Costo unitario contenuto anche su tirature da cinquanta pezzi.', ['sagoma', 'incisione-laser', 'anello'], true],
    ['Grecale', 'Portachiavi apribottiglie in acciaio', 'portachiavi', ['acciaio-inox'], ['marcatura-metalli', 'marcatura-metalli', 'taglio-laser'], { larghezza: '3 cm', altezza: '6,5 cm', spessore: '2 mm' }, ['gadget', 'aziendale'], 'both', 'Due funzioni in un pezzo solo da 2 mm di inox, marcato MOPA. È il gadget aziendale che sopravvive più a lungo nelle tasche.', ['logo', 'testo', 'colore marcatura']],
    ['Tramontana', 'Portachiavi NFC', 'portachiavi', ['compensato'], ['taglio-laser', 'incisione-laser'], { larghezza: '3,5 cm', altezza: '5,5 cm', spessore: '5 mm' }, ['gadget', 'tecnologia'], 'both', 'Chip NFC integrato che apre un contatto, un menù o un profilo social. Il contenuto si riprogramma senza rifare il portachiavi.', ['logo', 'URL', 'sagoma']],
    ['Maestrale', 'Calamita sagomata a due strati', 'calamite', ['compensato'], ['taglio-laser', 'taglio-laser', 'incisione-laser'], { larghezza: '6 cm', altezza: '6 cm', spessore: '6 mm' }, ['gadget', 'turismo', 'turismo'], 'both', 'Due strati sfalsati che creano profondità, con magnete al neodimio annegato sul retro — tiene anche su frigoriferi in acciaio spazzolato.', ['sagoma', 'incisione-laser', 'colori']],
    ['Ponente', 'Set calamite collezione città', 'calamite', ['compensato'], ['taglio-laser', 'incisione-laser', 'stampa-uv'], { larghezza: '5 cm', altezza: '7 cm', spessore: '5 mm' }, ['turismo', 'turismo', 'gadget'], 'b2b', 'Serie coordinata dedicata a una città o a un territorio, pensata per il retail turistico: espositore da banco incluso nella fornitura.', ['soggetti', 'numero pezzi', 'espositore']],
    ['Levante', 'Calamita apribottiglie', 'calamite', ['compensato', 'acciaio-inox'], ['taglio-laser', 'incisione-laser'], { larghezza: '5 cm', altezza: '8 cm', spessore: '10 mm' }, ['gadget', 'aziendale'], 'both', 'Apribottiglie sul frigorifero, dove serve davvero. Il magnete regge il peso del pezzo anche sotto trazione durante l\'apertura.', ['logo', 'incisione-laser', 'sagoma']],
    ['Ostro', 'Targa sagomata su misura', 'targhe-sagomate', ['compensato', 'plexiglass-colato'], ['taglio-laser', 'taglio-laser', 'incisione-laser'], { larghezza: 'a disegno', altezza: 'a disegno', spessore: '3–6 mm' }, ['gadget', 'aziendale', 'custom'], 'both', 'Taglio su profilo fornito dal cliente: qualunque sagoma chiusa è producibile senza costi di attrezzaggio, da un pezzo in su.', ['sagoma', 'materiale', 'incisione-laser']],
    ['Austro', 'Medaglietta identificativa per animali', 'targhe-sagomate', ['alluminio-anodizzato'], ['marcatura-metalli', 'marcatura-metalli', 'taglio-laser'], { diametro: '3 cm', spessore: '1,5 mm' }, ['regali', 'gadget'], 'b2c', 'Alluminio anodizzato con marcatura incisa fronte-retro: nome da un lato, recapito dall\'altro. Non si consuma contro il collare.', ['nome', 'recapito', 'colore']],
    ['Ciane', 'Segnalibro traforato in betulla', 'segnalibri', ['compensato'], ['taglio-laser', 'taglio-laser', 'incisione-laser'], { larghezza: '4 cm', altezza: '15 cm', spessore: '2 mm' }, ['gadget', 'regali'], 'both', 'Betulla da 2 mm con traforo passante: abbastanza sottile da non deformare la rilegatura, abbastanza rigido da non piegarsi.', ['grafica', 'testo', 'sagoma']],
    ['Alfeo', 'Segnalibro in metallo inciso', 'segnalibri', ['acciaio-inox'], ['marcatura-metalli', 'marcatura-metalli', 'taglio-laser'], { larghezza: '2,5 cm', altezza: '12 cm', spessore: '0,5 mm' }, ['regali', 'aziendale'], 'both', 'Lamina di inox da mezzo millimetro, incisa a colori MOPA. Peso e spessore studiati per non segnare la carta.', ['grafica', 'testo', 'colore marcatura']],
    ['Anapo', 'Spilla in legno con spilla di sicurezza', 'spille-pin', ['compensato'], ['taglio-laser', 'incisione-laser'], { larghezza: '4 cm', altezza: '4 cm', spessore: '4 mm' }, ['eventi', 'gadget'], 'both', 'Supporto in betulla con spilla metallica incollata a caldo. Usata soprattutto come riconoscimento per staff e volontari.', ['grafica', 'sagoma', 'testo']],
    ['Simeto', 'Pin aziendale in alluminio', 'spille-pin', ['alluminio-anodizzato'], ['marcatura-metalli', 'marcatura-metalli', 'taglio-laser'], { larghezza: '2 cm', altezza: '2 cm', spessore: '1,5 mm' }, ['aziendale'], 'b2b', 'Pin da giacca con marcatura a colori e attacco a farfalla. Riproduce marchi complessi con dettagli fino a 0,2 mm.', ['logo', 'colori', 'attacco']],
    ['Alcantara', 'Apribottiglie da tasca personalizzato', 'altri-gadget', ['compensato', 'acciaio-inox'], ['taglio-laser', 'incisione-laser'], { larghezza: '4 cm', altezza: '10 cm', spessore: '8 mm' }, ['gadget', 'aziendale'], 'both', 'Corpo in betulla incisa e lama in acciaio: più piacevole in mano dei gadget interamente metallici, e altrettanto efficace.', ['logo', 'incisione-laser', 'essenza']],
    ['Pollina', 'Set gadget welcome kit aziendale', 'altri-gadget', ['compensato'], ['taglio-laser', 'incisione-laser'], { larghezza: '25 cm', profondita: '18 cm', altezza: '6 cm' }, ['aziendale'], 'b2b', 'Scatola coordinata con più oggetti a scelta dal catalogo — portachiavi, sottobicchiere, biglietto NFC — pensata per l\'onboarding dei nuovi assunti.', ['composizione', 'logo', 'scatola']]
  ],

  /* ── CASA & ARREDAMENTO ─────────────────────────────────── */
  'casa': [
    ['Madonie', 'Appendiabiti da parete a cinque pomelli', 'appendiabiti', ['legno-massello', 'compensato'], ['taglio-laser', 'incisione-laser'], { larghezza: '60 cm', altezza: '12 cm', profondita: '8 cm' }, ['casa'], 'b2c', 'Pomelli in massello torniti e avvitati da dietro: nessuna vite a vista sul fronte e nessun rischio che il cappotto ci si impigli.', ['numero pomelli', 'essenza', 'incisione-laser'], true],
    ['Nebrodi', 'Appendiabiti verticale salvaspazio', 'appendiabiti', ['compensato'], ['taglio-laser', 'taglio-laser'], { larghezza: '15 cm', altezza: '80 cm', profondita: '8 cm' }, ['casa'], 'b2c', 'Sviluppo verticale per ingressi stretti dove un appendiabiti orizzontale non ci sta. Sei ganci sfalsati su due file.', ['numero ganci', 'colore', 'altezza']],
    ['Peloritani', 'Orologio da parete minimale', 'orologi', ['compensato'], ['taglio-laser', 'incisione-laser'], { diametro: '30 cm', spessore: '6 mm' }, ['casa', 'aziendale'], 'both', 'Quadrante in betulla con indici incisi e meccanismo silenzioso a sweep: nessun ticchettio, adatto a camere e uffici.', ['indici', 'incisione-laser', 'diametro']],
    ['Iblea', 'Orologio da parete a numeri sospesi', 'orologi', ['compensato', 'mdf'], ['taglio-laser', 'taglio-laser'], { diametro: '45 cm', spessore: '10 mm' }, ['casa'], 'b2c', 'Numeri tagliati singolarmente e applicati direttamente al muro attorno al meccanismo centrale: l\'orologio prende la dimensione che serve alla parete.', ['numeri', 'colore', 'diametro']],
    ['Etna', 'Pannello decorativo a rilievo', 'decorazioni-murali', ['compensato', 'mdf'], ['taglio-laser', 'incisione-laser'], { larghezza: '60 cm', altezza: '40 cm', spessore: '18 mm' }, ['casa', 'ristorazione'], 'both', 'Rilievo ottenuto per sovrapposizione di strati tagliati: la topografia di un territorio, un pattern geometrico o un\'illustrazione su misura.', ['soggetto', 'misura', 'finitura'], true],
    ['Stromboli', 'Lettere decorative componibili', 'decorazioni-murali', ['compensato'], ['taglio-laser', 'taglio-laser'], { altezza: '10–40 cm', spessore: '18 mm' }, ['casa', 'eventi'], 'both', 'Lettere singole in betulla, da appoggiare o appendere. Altezza e font a scelta, con supporto posteriore per il fissaggio a filo muro.', ['testo', 'font', 'altezza']],
    ['Panarea', 'Lampada da tavolo a diffusione', 'lampade', ['compensato', 'plexiglass-colato'], ['taglio-laser', 'taglio-laser'], { larghezza: '15 cm', profondita: '15 cm', altezza: '25 cm' }, ['casa', 'regali'], 'b2c', 'Struttura traforata in betulla su diffusore in acrilico opalino, LED a 12 V dimmerabile. La luce esce dal traforo e disegna la parete.', ['traforo', 'temperatura luce', 'misura']],
    ['Filicudi', 'Applique da parete in acrilico', 'lampade', ['plexiglass-colato', 'compensato'], ['taglio-laser', 'taglio-laser'], { larghezza: '30 cm', altezza: '15 cm', profondita: '8 cm' }, ['casa', 'turismo'], 'both', 'Luce indiretta verso l\'alto e verso il basso, senza abbagliamento diretto. Adatta a corridoi e testate di letto in strutture ricettive.', ['misura', 'temperatura luce', 'finitura']],
    ['Alicudi', 'Mensola a incastro senza viti', 'mensole', ['compensato', 'legno-massello'], ['taglio-laser', 'taglio-laser'], { larghezza: '60 cm', profondita: '18 cm', altezza: '20 cm' }, ['casa'], 'b2c', 'Struttura autoportante a incastro: due tasselli al muro e nessuna vite a vista. Portata verificata fino a otto chili distribuiti.', ['misura', 'essenza', 'finitura']],
    ['Levanzo', 'Mensola d\'angolo', 'mensole', ['compensato'], ['taglio-laser', 'taglio-laser'], { larghezza: '30 cm', profondita: '30 cm', altezza: '15 cm' }, ['casa'], 'b2c', 'Sfrutta l\'angolo, che è lo spazio che resta sempre inutilizzato. Montaggio su due pareti con squadrette annegate.', ['misura', 'colore', 'numero ripiani']],
    ['Marettimo', 'Portachiavi da parete con mensolina', 'portachiavi-parete', ['compensato', 'legno-massello'], ['taglio-laser', 'incisione-laser'], { larghezza: '30 cm', altezza: '15 cm', profondita: '8 cm' }, ['casa', 'regali'], 'b2c', 'Quattro ganci più un ripiano superiore per posta e occhiali: l\'ingresso resta sgombro senza dover aggiungere un secondo mobile.', ['numero ganci', 'incisione-laser', 'essenza']],
    ['Favara', 'Portachiavi da parete a ganci', 'portachiavi-parete', ['compensato'], ['taglio-laser', 'incisione-laser'], { larghezza: '25 cm', altezza: '8 cm', spessore: '12 mm' }, ['casa', 'turismo'], 'both', 'Versione essenziale a cinque ganci, personalizzabile con nome o numero. Usata anche nelle reception di piccole strutture ricettive.', ['numero ganci', 'testo', 'colore']],
    ['Bronte', 'Porta mestoli da parete', 'cucina-casa', ['legno-massello'], ['taglio-laser', 'taglio-laser'], { larghezza: '40 cm', altezza: '10 cm', profondita: '6 cm' }, ['casa'], 'b2c', 'Barra in massello con ganci in acciaio, finitura a olio alimentare. Libera il piano di lavoro dai contenitori di utensili.', ['numero ganci', 'essenza', 'misura']],
    ['Randazzo', 'Porta capsule da banco', 'cucina-casa', ['compensato', 'plexiglass-colato'], ['taglio-laser', 'taglio-laser'], { larghezza: '12 cm', profondita: '12 cm', altezza: '30 cm' }, ['casa', 'aziendale'], 'both', 'Colonna verticale con caricamento dall\'alto e prelievo dal basso: le capsule scendono per gravità e la prima inserita è la prima usata.', ['tipo capsula', 'capienza', 'incisione-laser']]
  ],

  /* ── INGLY KIDS ─────────────────────────────────────────── */
  'kids': [
    ['Girandola', 'Gioco a incastro animali', 'giochi-incastro', ['compensato'], ['taglio-laser', 'taglio-laser'], { larghezza: '20 cm', altezza: '20 cm', spessore: '9 mm' }, ['regali'], 'b2c', 'Sagome che entrano solo nella sede corretta, con spessore da 9 mm perché siano afferrabili da mani piccole. Spigoli arrotondati a mano e finitura atossica.', ['soggetti', 'nome', 'colori'], true],
    ['Aquilone', 'Costruzioni a incastro set base', 'giochi-incastro', ['compensato'], ['taglio-laser', 'taglio-laser'], { pezzi: '48', spessore: '4 mm' }, ['regali'], 'b2c', 'Quarantotto elementi con cave laterali che si incastrano in qualsiasi direzione. Nessuna istruzione: la regola la scopre chi gioca.', ['numero pezzi', 'colori', 'astuccio']],
    ['Trottola', 'Puzzle sagomato personalizzato', 'puzzle', ['compensato'], ['taglio-laser', 'taglio-laser', 'incisione-laser'], { larghezza: '25 cm', altezza: '20 cm', spessore: '4 mm' }, ['regali'], 'b2c', 'Tagliato su un\'immagine fornita dal cliente, con numero di pezzi scelto in base all\'età. Ogni taglio è unico, quindi i pezzi non sono intercambiabili.', ['immagine', 'numero pezzi', 'nome']],
    ['Altalena', 'Puzzle alfabeto', 'puzzle', ['compensato'], ['taglio-laser', 'taglio-laser'], { larghezza: '30 cm', altezza: '22 cm', spessore: '6 mm' }, ['regali'], 'b2c', 'Ventisei lettere che escono dalla tavola e si rimettono a posto. La tavola resta leggibile anche a lettere estratte, per confrontare la forma con la sede.', ['colori', 'font', 'nome']],
    ['Ninna', 'Decorazione nome per cameretta', 'cameretta', ['compensato'], ['taglio-laser', 'taglio-laser'], { larghezza: '40 cm', altezza: '15 cm', spessore: '9 mm' }, ['regali'], 'b2c', 'Nome tagliato in corsivo continuo, con il tratto calcolato per reggere il peso senza punti fragili fra una lettera e l\'altra.', ['nome', 'font', 'colore']],
    ['Filastrocca', 'Metro altezza da parete', 'cameretta', ['compensato'], ['taglio-laser', 'incisione-laser'], { larghezza: '20 cm', altezza: '120 cm', spessore: '9 mm' }, ['regali'], 'b2c', 'Scala graduata incisa da 60 a 180 cm, con tacche ogni centimetro. Si segna la crescita direttamente sul legno, senza matita.', ['nome', 'grafica', 'colore']],
    ['Abaco', 'Pallottoliere didattico', 'giochi-educativi', ['compensato'], ['taglio-laser', 'taglio-laser'], { larghezza: '30 cm', altezza: '25 cm', profondita: '8 cm' }, ['regali'], 'b2c', 'Dieci aste da dieci sfere su telaio autoportante. Le sfere scorrono con attrito calibrato: restano dove vengono lasciate.', ['colori', 'numero aste', 'incisione-laser']],
    ['Sillaba', 'Tavoletta lettere componibili', 'giochi-educativi', ['compensato'], ['taglio-laser', 'taglio-laser', 'incisione-laser'], { larghezza: '30 cm', altezza: '20 cm', spessore: '6 mm' }, ['regali'], 'b2c', 'Tessere-lettera che si compongono nella guida della tavoletta per formare parole. Set base di sessanta tessere con vocali in doppia copia.', ['numero tessere', 'colori', 'nome']]
  ],

  /* ── ARTE & MOVIMENTO ───────────────────────────────────── */
  'arte-movimento': [
    ['Efesto', 'Automa a manovella con figura', 'automi', ['compensato', 'compensato'], ['taglio-laser', 'taglio-laser'], { larghezza: '20 cm', profondita: '15 cm', altezza: '25 cm' }, ['regali', 'custom'], 'b2c', 'Un giro di manovella e la figura compie il suo ciclo completo. Camme e bielle sono tagliate a 0,1 mm di tolleranza: sotto quella soglia il meccanismo si inceppa.', ['soggetto', 'finitura', 'incisione-laser'], true],
    ['Encelado', 'Automa marino a camme', 'automi', ['compensato'], ['taglio-laser', 'taglio-laser'], { larghezza: '25 cm', profondita: '15 cm', altezza: '20 cm' }, ['regali', 'turismo'], 'b2c', 'Tre camme sfasate producono un moto ondulatorio continuo: le figure salgono e scendono in tempi diversi e il ciclo non sembra mai ripetersi.', ['soggetto', 'finitura', 'base']],
    ['Polifemo', 'Meccanismo didattico a ingranaggi', 'meccanismi', ['compensato'], ['taglio-laser', 'taglio-laser', 'incisione-laser'], { larghezza: '30 cm', altezza: '30 cm', spessore: '9 mm' }, ['regali', 'custom'], 'both', 'Rotismo a vista con rapporti di riduzione incisi accanto a ogni ruota. Nato come oggetto didattico, funziona altrettanto bene come pezzo da parete.', ['rapporti', 'misura', 'finitura']],
    ['Galatea', 'Meccanismo a biella su base', 'meccanismi', ['compensato', 'legno-massello'], ['taglio-laser', 'taglio-laser'], { larghezza: '22 cm', profondita: '12 cm', altezza: '18 cm' }, ['regali'], 'b2c', 'Conversione del moto rotatorio in moto alternato, con corsa regolabile spostando il perno di biella su tre posizioni.', ['finitura', 'base', 'incisione-laser']],
    ['Dafne', 'Scultura cinetica da tavolo', 'sculture-cinetiche', ['compensato', 'acciaio-inox'], ['taglio-laser', 'taglio-laser'], { larghezza: '20 cm', profondita: '20 cm', altezza: '35 cm' }, ['casa', 'regali'], 'b2c', 'Elementi bilanciati su perni in acciaio che restano in movimento diversi minuti dopo la spinta iniziale, per pura inerzia.', ['finitura', 'misura', 'base']],
    ['Cariddi', 'Scultura a vortice rotante', 'sculture-cinetiche', ['compensato'], ['taglio-laser', 'taglio-laser'], { diametro: '25 cm', altezza: '30 cm' }, ['casa', 'turismo'], 'b2c', 'Ventiquattro lamelle sfalsate progressivamente: in rotazione l\'occhio legge una spirale continua che nella forma statica non esiste.', ['numero lamelle', 'finitura', 'base']]
  ],

  /* ── INGLY TECH ─────────────────────────────────────────── */
  'tech': [
    ['Vettore', 'Porta QR da parete', 'qr-code', ['compensato', 'alluminio-anodizzato'], ['taglio-laser', 'incisione-laser'], { larghezza: '15 cm', altezza: '20 cm', spessore: '10 mm' }, ['ristorazione', 'tecnologia', 'turismo'], 'b2b', 'QR inciso su pannello da parete con testo di istruzione sotto. Altezza di montaggio consigliata 140 cm, la più comoda per inquadrare da fermi.', ['QR', 'testo', 'logo'], true],
    ['Impulso', 'Targhetta QR adesiva per tavolo', 'qr-code', ['plexiglass-colato'], ['taglio-laser', 'incisione-laser', 'taglio-laser'], { larghezza: '5 cm', altezza: '5 cm', spessore: '3 mm' }, ['ristorazione', 'tecnologia'], 'b2b', 'Plexiglass inciso con adesivo strutturale sul retro: si applica al tavolo e resta, ma si rimuove senza lasciare residui a fine stagione.', ['QR', 'logo', 'colore']],
    ['Segnale', 'Tag NFC universale', 'tag-nfc', ['compensato'], ['taglio-laser', 'incisione-laser'], { diametro: '4 cm', spessore: '5 mm' }, ['tecnologia', 'aziendale'], 'both', 'Disco NTAG215 riprogrammabile: apre un sito, un contatto o una rete wifi. Si riscrive quante volte serve dallo smartphone.', ['URL', 'incisione-laser', 'diametro']],
    ['Frequenza', 'Tag NFC per vetrina', 'tag-nfc', ['plexiglass-colato'], ['taglio-laser', 'incisione-laser'], { larghezza: '8 cm', altezza: '8 cm', spessore: '5 mm' }, ['tecnologia', 'ristorazione'], 'b2b', 'Applicato all\'interno del vetro, funziona dall\'esterno: il cliente accede alle informazioni anche a locale chiuso.', ['URL', 'grafica', 'misura']],
    ['Circuito', 'Biglietto da visita NFC in alluminio', 'biglietti-nfc', ['alluminio-anodizzato'], ['marcatura-metalli', 'marcatura-metalli', 'taglio-laser'], { larghezza: '8,6 cm', altezza: '5,4 cm', spessore: '1 mm' }, ['aziendale', 'tecnologia'], 'b2b', 'Alluminio anodizzato con marcatura MOPA e chip integrato. Peso e finitura fanno la differenza al primo scambio di mano.', ['logo', 'URL', 'colore anodizzazione'], true],
    ['Modulo', 'Biglietto da visita NFC in plexiglass', 'biglietti-nfc', ['plexiglass-colato'], ['taglio-laser', 'incisione-laser', 'taglio-laser'], { larghezza: '8,6 cm', altezza: '5,4 cm', spessore: '1,5 mm' }, ['aziendale', 'tecnologia'], 'b2b', 'Trasparente con incisione sul retro che si legge in rilievo dal fronte. Chip NFC laminato fra due strati.', ['logo', 'URL', 'colore']],
    ['Antenna', 'Totem informativo da banco', 'totem-informativi', ['compensato', 'plexiglass-colato'], ['taglio-laser', 'incisione-laser'], { larghezza: '15 cm', profondita: '12 cm', altezza: '30 cm' }, ['turismo', 'ristorazione', 'tecnologia'], 'b2b', 'Colonna da reception con QR, NFC e tasca per materiale cartaceo: copre chi usa il telefono e chi preferisce ancora la carta.', ['contenuti', 'logo', 'misura']],
    ['Diodo', 'Totem da terra per accoglienza', 'totem-informativi', ['compensato', 'mdf'], ['taglio-laser'], { larghezza: '40 cm', profondita: '40 cm', altezza: '140 cm' }, ['turismo', 'eventi'], 'b2b', 'Struttura smontabile con pannelli sostituibili e QR incisi. Trasportabile in auto senza smontare la base.', ['contenuti', 'altezza', 'colori']],
    ['Consenso', 'Placca recensioni da banco', 'recensioni', ['compensato', 'alluminio-anodizzato'], ['taglio-laser', 'incisione-laser'], { larghezza: '10 cm', altezza: '14 cm', spessore: '15 mm' }, ['ristorazione', 'turismo', 'tecnologia'], 'b2b', 'NFC e QR verso la pagina recensioni, con base inclinata da appoggiare accanto alla cassa. Il momento giusto per chiedere è quello del pagamento.', ['piattaforma', 'logo', 'testo']],
    ['Riscontro', 'Espositore recensioni a bandiera', 'recensioni', ['compensato'], ['taglio-laser', 'incisione-laser'], { larghezza: '12 cm', altezza: '16 cm', sporgenza: '15 cm' }, ['ristorazione', 'tecnologia'], 'b2b', 'Versione a parete perpendicolare, visibile lungo il percorso di uscita. Bifacciale, con QR su entrambi i lati.', ['piattaforma', 'logo', 'staffa']]
  ],

  /* ── CARTA & PACKAGING ──────────────────────────────────── */
  'carta-packaging': [
    ['Origami', 'Scatola pieghevole su misura', 'scatole', ['compensato'], ['taglio-laser', 'taglio-laser', 'stampa-uv'], { larghezza: '20 cm', profondita: '15 cm', altezza: '8 cm' }, ['aziendale', 'regali'], 'b2b', 'Fustella disegnata sul prodotto reale e tagliata al laser: nessun costo di attrezzaggio, quindi conviene già da cinquanta pezzi.', ['misura', 'stampa', 'materiale'], true],
    ['Piega', 'Scatola a fondo automatico', 'scatole', ['compensato'], ['taglio-laser', 'taglio-laser'], { larghezza: '25 cm', profondita: '18 cm', altezza: '10 cm' }, ['aziendale'], 'b2b', 'Il fondo si forma da solo aprendo la scatola: chi confeziona guadagna qualche secondo a pezzo, che su mille spedizioni è mezza giornata.', ['misura', 'stampa', 'grammatura']],
    ['Cartiglio', 'Cartellino prodotto traforato', 'cartellini', ['compensato'], ['taglio-laser', 'taglio-laser', 'incisione-laser'], { larghezza: '5 cm', altezza: '8 cm', grammatura: '350 g/m²' }, ['aziendale', 'gadget'], 'b2b', 'Cartoncino da 350 g con traforo passante e foro per il cordino. Il taglio laser sigilla il bordo, che quindi non sfilaccia.', ['grafica', 'misura', 'cordino']],
    ['Filigrana', 'Cartellino appendibile in cartoncino', 'cartellini', ['compensato'], ['taglio-laser', 'taglio-laser', 'stampa-uv'], { larghezza: '4 cm', altezza: '9 cm', grammatura: '300 g/m²' }, ['aziendale', 'regali'], 'b2b', 'Stampa UV a colori pieni più taglio sagomato. Adatto a etichettatura di prodotto, prezzi e istruzioni di lavaggio.', ['grafica', 'sagoma', 'stampa']],
    ['Pergamena', 'Invito traforato per matrimonio', 'inviti', ['compensato'], ['taglio-laser', 'taglio-laser', 'incisione-laser'], { larghezza: '14 cm', altezza: '20 cm', grammatura: '300 g/m²' }, ['wedding'], 'b2c', 'Traforo a motivo continuo su cartoncino avorio, con cartiglio interno stampato. Ogni invito è tagliato singolarmente.', ['grafica', 'testo']],
    ['Miniatura', 'Invito a strati per evento', 'inviti', ['compensato'], ['taglio-laser', 'taglio-laser'], { larghezza: '15 cm', altezza: '15 cm', spessore: '3 mm' }, ['eventi', 'wedding'], 'both', 'Cartoncino e velo di betulla sovrapposti: il contrasto fra i due materiali si sente in mano prima ancora di leggere il testo.', ['grafica', 'materiali', 'testo']],
    ['Fascia', 'Sleeve per packaging', 'fascette', ['compensato'], ['taglio-laser', 'taglio-laser', 'stampa-uv'], { larghezza: '30 cm', altezza: '8 cm', grammatura: '250 g/m²' }, ['aziendale'], 'b2b', 'Fascia che chiude una confezione neutra e la rende riconoscibile: il modo più economico per personalizzare un packaging standard.', ['grafica', 'misura', 'stampa']],
    ['Nastro', 'Fascetta portaposate per catering', 'fascette', ['compensato'], ['taglio-laser', 'taglio-laser', 'stampa-uv'], { larghezza: '18 cm', altezza: '4 cm', grammatura: '200 g/m²' }, ['ristorazione', 'eventi'], 'b2b', 'Tiene insieme tovagliolo e posate e porta il marchio del locale. Prodotta in tirature da cinquecento pezzi in su.', ['grafica', 'misura', 'stampa']]
  ],

  /* ── PLEXI & METALLO ────────────────────────────────────── */
  'plexi-metallo': [
    ['Prisma', 'Espositore in plexiglass trasparente', 'plexiglass-colato', ['plexiglass-colato'], ['taglio-laser', 'taglio-laser'], { larghezza: '20 cm', profondita: '15 cm', altezza: '25 cm' }, ['ristorazione', 'aziendale'], 'b2b', 'Piegato a caldo su stampo, senza giunzioni incollate: la trasparenza resta continua e non si vedono le linee di colla invecchiare.', ['misura', 'spessore', 'incisione-laser'], true],
    ['Lastra', 'Targa in plexiglass a distanziali', 'plexiglass-colato', ['plexiglass-colato', 'acciaio-inox'], ['taglio-laser', 'incisione-laser'], { larghezza: '30 cm', altezza: '20 cm', spessore: '8 mm' }, ['aziendale'], 'b2b', 'Lastra da 8 mm staccata dal muro con distanziali in acciaio: l\'ombra proiettata dietro la targa fa risaltare l\'incisione.', ['testo', 'logo', 'misura']],
    ['Lumen', 'Insegna retroilluminata a bordo luce', 'acrilico-retroilluminato', ['plexiglass-colato', 'alluminio-anodizzato'], ['taglio-laser', 'incisione-laser'], { larghezza: '50 cm', altezza: '30 cm', spessore: '20 mm' }, ['ristorazione', 'aziendale'], 'b2b', 'LED sul bordo e incisione sulla superficie: la luce viaggia dentro la lastra e si accende solo dove il laser ha inciso.', ['grafica', 'misura', 'colore luce']],
    ['Aura', 'Pannello luminoso da parete', 'acrilico-retroilluminato', ['plexiglass-colato', 'compensato'], ['taglio-laser', 'taglio-laser'], { larghezza: '60 cm', altezza: '40 cm', spessore: '40 mm' }, ['casa', 'ristorazione'], 'both', 'Diffusore opalino su cassa in betulla con LED dimmerabile. Luce uniforme senza punti caldi, adatta anche come illuminazione d\'ambiente.', ['grafica', 'misura', 'temperatura luce']],
    ['Anodo', 'Targa tecnica in alluminio anodizzato', 'alluminio-anodizzato', ['alluminio-anodizzato'], ['marcatura-metalli', 'marcatura-metalli', 'taglio-laser'], { larghezza: '10 cm', altezza: '5 cm', spessore: '1 mm' }, ['aziendale'], 'b2b', 'Marcatura a fibra su anodizzato nero: bianco pieno, contrasto massimo, resistenza a solventi e raggi UV. Standard per matricole e dati tecnici.', ['dati', 'numerazione', 'misura']],
    ['Lamina', 'Placca in alluminio spazzolato', 'alluminio-anodizzato', ['alluminio-anodizzato'], ['marcatura-metalli', 'marcatura-metalli'], { larghezza: '15 cm', altezza: '10 cm', spessore: '1,5 mm' }, ['aziendale', 'turismo'], 'b2b', 'Finitura spazzolata che nasconde le impronte, marcatura permanente. Adatta ad ambienti ad alta frequentazione.', ['testo', 'logo', 'misura']],
    ['Tempra', 'Targa in acciaio inox marcata MOPA', 'acciaio-inox', ['acciaio-inox'], ['marcatura-metalli', 'marcatura-metalli'], { larghezza: '20 cm', altezza: '15 cm', spessore: '1,5 mm' }, ['aziendale', 'regali'], 'b2b', 'Colori reali ottenuti per ossidazione controllata: blu, viola, ambra e bronzo senza un grammo di inchiostro. Nessuna stampa regge lo stesso confronto nel tempo.', ['grafica', 'colori', 'misura'], true],
    ['Filo', 'Segnaposto in acciaio inciso', 'acciaio-inox', ['acciaio-inox'], ['marcatura-metalli', 'marcatura-metalli', 'taglio-laser'], { larghezza: '8 cm', altezza: '3 cm', spessore: '0,8 mm' }, ['wedding', 'eventi'], 'both', 'Lamina sottile con nome inciso e piega a cavalletto. Riutilizzabile evento dopo evento, a differenza del cartoncino.', ['nome', 'font', 'colore marcatura']],
    ['Innesto', 'Targa combinata legno e alluminio', 'combinati', ['compensato', 'alluminio-anodizzato'], ['taglio-laser', 'marcatura-metalli'], { larghezza: '30 cm', altezza: '20 cm', spessore: '15 mm' }, ['aziendale', 'ristorazione'], 'b2b', 'Fondo in betulla e placca in alluminio incassata a filo: il calore del legno e la precisione del metallo sullo stesso pezzo.', ['testo', 'logo', 'misura']],
    ['Giunzione', 'Espositore legno e plexiglass', 'combinati', ['compensato', 'plexiglass-colato'], ['taglio-laser', 'taglio-laser'], { larghezza: '25 cm', profondita: '18 cm', altezza: '30 cm' }, ['ristorazione', 'eventi'], 'b2b', 'Struttura portante in betulla e tasche trasparenti in plexiglass: il contenuto resta in evidenza, la struttura resta riconoscibile.', ['misura', 'numero tasche', 'incisione-laser']]
  ],

  /* ── EVENTI & B2B ───────────────────────────────────────── */
  'eventi': [
    ['Vendicari', 'Tableau de mariage a pannello unico', 'wedding', ['compensato'], ['taglio-laser', 'incisione-laser'], { larghezza: '70 cm', altezza: '100 cm', spessore: '9 mm' }, ['wedding'], 'b2c', 'Pannello unico con tutti i nomi incisi, senza tessere applicate. Richiede la lista definitiva ma dà un risultato che nessuna composizione modulare eguaglia.', ['nomi', 'grafica', 'misura'], true],
    ['Portopalo', 'Segnaposto matrimonio inciso', 'wedding', ['compensato'], ['taglio-laser', 'taglio-laser', 'incisione-laser'], { larghezza: '9 cm', altezza: '5 cm', spessore: '3 mm' }, ['wedding'], 'b2c', 'Nome inciso singolarmente su sagoma a scelta, consegnato in ordine alfabetico e diviso per tavolo: chi allestisce trova tutto già organizzato.', ['nomi', 'sagoma', 'font']],
    ['Avola', 'Ventaglio programma cerimonia', 'wedding', ['compensato'], ['taglio-laser', 'taglio-laser', 'incisione-laser'], { larghezza: '20 cm', altezza: '25 cm', spessore: '3 mm' }, ['wedding'], 'b2c', 'Programma della cerimonia su ventaglio rigido: risolve il problema del caldo nelle celebrazioni estive all\'aperto e resta come ricordo.', ['testo', 'grafica', 'misura']],
    ['Eloro', 'Porta fedi a incastro', 'wedding', ['compensato', 'legno-massello'], ['taglio-laser', 'taglio-laser'], { larghezza: '12 cm', profondita: '8 cm', altezza: '5 cm' }, ['wedding'], 'b2c', 'Due sedi sagomate e coperchio a scorrimento, montato a incastro senza colla. Le fedi restano ferme anche se il cuscino si inclina.', ['incisione-laser', 'essenza', 'data']],
    ['Camarina', 'Espositore da stand a colonna', 'fiere-stand', ['compensato', 'mdf'], ['taglio-laser'], { larghezza: '40 cm', profondita: '40 cm', altezza: '180 cm' }, ['eventi', 'aziendale'], 'b2b', 'Smontabile in sei pannelli piatti che entrano in un\'auto normale. Montaggio in dieci minuti senza attrezzi.', ['grafica', 'altezza', 'colori']],
    ['Morgantina', 'Porta brochure da terra', 'fiere-stand', ['compensato', 'plexiglass-colato'], ['taglio-laser', 'taglio-laser'], { larghezza: '25 cm', profondita: '30 cm', altezza: '120 cm' }, ['eventi', 'aziendale'], 'b2b', 'Quattro tasche A4 su colonna zavorrata: non si ribalta in un corridoio affollato, che è il difetto tipico dei porta brochure leggeri.', ['numero tasche', 'logo', 'colore']],
    ['Pantalica', 'Badge accredito in betulla', 'badge-accrediti', ['compensato'], ['taglio-laser', 'incisione-laser', 'taglio-laser'], { larghezza: '9 cm', altezza: '6 cm', spessore: '3 mm' }, ['eventi', 'aziendale'], 'b2b', 'Badge nominativo inciso uno per uno, con foro per cordino. Più solido del PVC e riconoscibile a colpo d\'occhio dallo staff.', ['nomi', 'ruoli', 'logo']],
    ['Sortino', 'Porta badge con cordino', 'badge-accrediti', ['plexiglass-colato'], ['taglio-laser', 'taglio-laser', 'incisione-laser'], { larghezza: '10 cm', altezza: '7 cm', spessore: '3 mm' }, ['eventi'], 'b2b', 'Custodia trasparente per badge cartacei intercambiabili: si riusa a ogni edizione dell\'evento cambiando solo l\'inserto.', ['logo', 'misura', 'cordino']],
    ['Ferla', 'Premio a lastra su base', 'premi-targhe', ['plexiglass-colato', 'legno-massello'], ['taglio-laser', 'incisione-laser'], { larghezza: '15 cm', altezza: '25 cm', profondita: '8 cm' }, ['eventi', 'aziendale'], 'b2b', 'Lastra in plexiglass incisa su base in massello. L\'incisione interna si illumina se la base viene predisposta con LED.', ['testo', 'logo', 'base']],
    ['Buscemi', 'Targa ricordo commemorativa', 'premi-targhe', ['compensato', 'alluminio-anodizzato'], ['taglio-laser', 'marcatura-metalli'], { larghezza: '25 cm', altezza: '18 cm', spessore: '15 mm' }, ['eventi', 'aziendale'], 'b2b', 'Fondo in betulla con placca in alluminio marcata: il testo commemorativo resta leggibile anche a decenni di distanza.', ['testo', 'logo', 'misura']],
    ['Buccheri', 'Backdrop modulare per photo booth', 'allestimenti', ['compensato', 'mdf'], ['taglio-laser'], { larghezza: '200 cm', altezza: '200 cm', spessore: '18 mm' }, ['eventi', 'wedding'], 'b2b', 'Pannelli componibili su telaio autoportante, con marchio a rilievo. Si monta in mezz\'ora e si smonta in pezzi trasportabili da una persona sola.', ['grafica', 'misura', 'colori']],
    ['Militello', 'Segnaletica evento componibile', 'allestimenti', ['compensato'], ['taglio-laser', 'incisione-laser'], { larghezza: '30 cm', altezza: '40 cm', spessore: '9 mm' }, ['eventi'], 'b2b', 'Set di cartelli su asta con testi intercambiabili a inserto: lo stesso kit copre più eventi cambiando solo le tessere incise.', ['testi', 'numero pezzi', 'altezza']]
  ]
};
